- name: Testing
  uses: snakemake/snakemake-github-action@v1
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--lint'

- name: Testing
  uses: snakemake/snakemake-github-action@v1
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
    stagein: '' # additional preliminary commands to run (can be multiline)
    show-disk-usage-on-error: true


- name: Create container file
  uses: snakemake/snakemake-github-action@v1
  with:
    snakefile: 'workflow/Snakefile'
    task: 'containerize'
